# Generated by Django 3.0.11 on 2020-11-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='챔피언 군 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Champ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='챔피언 이름')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='챔피언 번호')),
                ('blue_WR', models.FloatField(blank=True, null=True, verbose_name='블루팀 승률')),
                ('red_WR', models.FloatField(blank=True, null=True, verbose_name='레드팀 승률')),
                ('more_50_WR', models.FloatField(blank=True, null=True, verbose_name='50판 이상 승률')),
                ('AFK_rate', models.FloatField(blank=True, null=True, verbose_name='탈주자 정도')),
                ('champ_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='champ_role', to='champs.ChampRole', verbose_name='챔피언 군 이름')),
            ],
        ),
    ]
