# Generated by Django 3.0.11 on 2020-11-25 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummonerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner1', models.TextField(blank=True, null=True, verbose_name='입력된 소환사 아이디1')),
                ('summoner2', models.TextField(blank=True, null=True, verbose_name='입력된 소환사 아이디2')),
                ('summoner3', models.TextField(blank=True, null=True, verbose_name='입력된 소환사 아이디3')),
                ('summoner4', models.TextField(blank=True, null=True, verbose_name='입력된 소환사 아이디4')),
                ('summoner5', models.TextField(blank=True, null=True, verbose_name='입력된 소환사 아이디5')),
            ],
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_top_summoner', models.TextField(blank=True, null=True, verbose_name='우리팀 탑 소환사 이름')),
                ('our_jungle_summoner', models.TextField(blank=True, null=True, verbose_name='우리팀 정글 소환사 이름')),
                ('our_middle_summoner', models.TextField(blank=True, null=True, verbose_name='우리팀 미드 소환사 이름')),
                ('our_carry_summoner', models.TextField(blank=True, null=True, verbose_name='우리팀 원딜 소환사 이름')),
                ('our_support_summoner', models.TextField(blank=True, null=True, verbose_name='우리팀 서포터 소환사 이름')),
                ('team_id', models.IntegerField(blank=True, null=True, verbose_name='팀 ID')),
                ('counter_carry_champ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_carry_champ', to='champs.Champ', verbose_name='상대팀 원딜 챔피언')),
                ('counter_jungle_champ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_jungle_champs', to='champs.Champ', verbose_name='상대팀 정글 챔피언')),
                ('counter_middle_champ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_middle_champ', to='champs.Champ', verbose_name='상대팀 미드 챔피언')),
                ('counter_support_champ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_support_champ', to='champs.Champ', verbose_name='상대팀 서포터 챔피언')),
                ('counter_top_champ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_top_champs', to='champs.Champ', verbose_name='상대팀 탑 챔피언')),
                ('our_carry_champ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_carry_champ', to='champs.Champ', verbose_name='우리팀 원딜 챔피언')),
                ('our_jungle_champ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_jungle_champs', to='champs.Champ', verbose_name='우리팀 정글 챔피언')),
                ('our_middle_champ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_middle_champs', to='champs.Champ', verbose_name='우리팀 미드 챔피언')),
                ('our_support_champ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_support_champs', to='champs.Champ', verbose_name='우리팀 서포터 챔피언')),
                ('our_top_champ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_top_champs', to='champs.Champ', verbose_name='우리팀 탑 챔피언')),
            ],
        ),
    ]
